# config.py

import os

class Config:
    SECRET_KEY = os.environ.get('SECRET_KEY')
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')
    SQLALCHEMY_TRACK_MODIFICATIONS = False 

    REMEMBER_COOKIE_DURATION = 3600 
    REMEMBER_COOKIE_SECURE = True 
    REMEMBER_COOKIE_HTTPONLY = True 
    REMEMBER_COOKIE_SAMESITE = 'Lax' 